download_dir: /tmp/

categories:
  School:
    path: Documents/School/
    prompt_subfolder: true
  Scouts:
    path: Documents/Scouts/
    prompt_subfolder: true
  Coding:
    path: Development/Downlaods/
    prompt_subfolder: false
  Music:
    path: Music/
    prompt_subfolder: false
  Pictures:
    path: Pictures/
    prompt_subfolder: false
  Videos:
    path: Videos/
    prompt_subfolder: false

ignore_files:
  - .DS_Store
  - .crdownload
  - .part
  - .tmp
  - .download
  - .temp
  - .opdownload